# Generated by Django 4.2.1 on 2023-07-13 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usuario_alter_datoscontacto_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(default='USER', max_length=20),
        ),
    ]
