# Generated by Django 4.2.1 on 2023-07-14 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_usuario_options_alter_usuario_actualizado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='password_decode',
            field=models.CharField(max_length=500, null=True, verbose_name='Password_Hash'),
        ),
    ]
