# Generated by Django 4.2.1 on 2023-07-10 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0008_alter_concierto_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concierto',
            name='fecha',
            field=models.DateTimeField(max_length=60, verbose_name='Fecha'),
        ),
    ]
